In [1]:
import numpy as np

# The Dynamics of Internal Migration in S. Korea: A Markov Chain Analysis

<img src="https://velog.velcdn.com/images/neoseurae12/post/c5bd58b7-0033-4850-a198-000ea5bba435/image.jpeg" width="420px">

In [2]:
state = {
    0: "Seoul",
    1: "Metropolitan",
    2: "Rural"
}
state

{0: 'Seoul', 1: 'Metropolitan', 2: 'Rural'}

## Transition Matrix
<img src="https://velog.velcdn.com/images/neoseurae12/post/c2b43497-b224-45bf-97a8-bb8063be890e/image.jpeg" width="350px">
<img src="https://velog.velcdn.com/images/neoseurae12/post/e45935ed-7cb5-4509-a30e-69f7edd48f30/image.jpeg" width="350px">

In [3]:
A = np.array(
    [[0.646, 0.246, 0.108],
    [0.106, 0.796, 0.098],
    [0.046, 0.066, 0.888]])
A

array([[0.646, 0.246, 0.108],
       [0.106, 0.796, 0.098],
       [0.046, 0.066, 0.888]])

## Random Walk on Markov Chain

In [4]:
n = 12
start_state = 2
print(state[start_state], "--->", end=" ")
prev_state = start_state

while n - 1:
    curr_state = np.random.choice([0, 1, 2], p=A[prev_state])
    print(state[curr_state], "--->", end=" ")
    prev_state = curr_state
    n -= 1
print("stop")

Rural ---> Rural ---> Rural ---> Rural ---> Rural ---> Rural ---> Metropolitan ---> Metropolitan ---> Rural ---> Rural ---> Rural ---> Rural ---> stop


## Approach 1: Monte Carlo

In [5]:
steps = 10**6
start_state = 0
pi = np.array([0, 0, 0])
pi[start_state] = 1
prev_state = start_state

i = 0
while i < steps:
    curr_state = np.random.choice([0, 1, 2], p=A[prev_state])
    pi[curr_state] += 1
    prev_state = curr_state
    i += 1

print("π = \n", pi/steps)

π = 
 [0.168099 0.358422 0.47348 ]


## Approach 2: Repeated Matrix Multiplication

In [6]:
# steps = 10**3
# A_n = A

# i = 0
# while i < steps:
#     A_n = np.matmul(A_n, A)
#     i += 1
    
# print("A^n = \n", A_n, "\n")
# print("π = ", A_n[0])

steps = 10
A_n = A

i = 0
while i < steps:
    A_n = np.matmul(A_n, A)
    i += 1

    print("A^n = \n", A_n, "\n")
    print("π = ", A_n[0])


A^n = 
 [[0.44836 0.36186 0.18978]
 [0.15736 0.66616 0.17648]
 [0.07756 0.12246 0.79998]] 

π =  [0.44836 0.36186 0.18978]
A^n = 
 [[0.3367276 0.4108626 0.2524098]
 [0.1803856 0.5806216 0.2389928]
 [0.0998836 0.1693566 0.7307598]] 

π =  [0.3367276 0.4108626 0.2524098]
A^n = 
 [[0.27268832 0.42654067 0.30077102]
 [0.18906866 0.52232318 0.28860817]
 [0.11609156 0.20760937 0.67629908]] 

π =  [0.27268832 0.42654067 0.30077102]
A^n = 
 [[0.23520543 0.42645858 0.33833599]
 [0.19078058 0.48132828 0.32789114]
 [0.1281115  0.23845132 0.63343719]] 

π =  [0.23520543 0.42645858 0.33833599]
A^n = 
 [[0.21271077 0.41965174 0.36763748]
 [0.18934805 0.45171015 0.35894181]
 [0.13717398 0.26312953 0.59969649]] 

π =  [0.21271077 0.41965174 0.36763748]
A^n = 
 [[0.19880557 0.41063371 0.39056072]
 [0.18671144 0.42983106 0.38345751]
 [0.14409216 0.28277587 0.57313197]] 

π =  [0.19880557 0.41063371 0.39056072]
A^n = 
 [[0.18992136 0.40154761 0.40853102]
 [0.18381673 0.41338473 0.40279854]
 [0.14942185 0

## Approach 3: Finding Left Eigen Vectors

In [7]:
import scipy.linalg
values, left = scipy.linalg.eig(A, right=False, left=True)

print("left eigen vectors = \n", left, "\n")
print("eigen values = \n", values)

left eigen vectors = 
 [[ 0.72122223 -0.27300355 -0.18966169]
 [-0.69209094 -0.57800751 -0.59293462]
 [-0.02913129 -0.76901     0.78259631]] 

eigen values = 
 [0.54242349+0.j 1.        +0.j 0.78757651+0.j]


In [8]:
pi = left[:,0]
pi_normalized = [(x/np.sum(pi)).real for x in pi]
pi_normalized

[3248096149779291.0, -3116900496653948.0, -131195653125342.0]

# Prediction: 2011-2022

In [28]:
seoul_prev = 10_249_679
metropolitan_prev = 14_738_689
rural_prev = 25_745_916

mover = [[1_834_806, 2_457_381, 3_835_008], 
         [1658928, 2303081, 3544682], 
         [1620640, 2260881, 3530263],
         [1661425, 2277352, 3690321],
         [1726687, 2361997, 3666602],
         [1655859, 2260845, 3461726],
         [1571423, 2183297, 3399506],
         [1549937, 2305327, 3441835],
         [1476081, 2228647, 3399670],
         [1642977, 2444503, 3648011],
         [1524430, 2307412, 3381580],
         [1236867, 1969147, 2946141]]

for i in range(2011, 2023):
    seoul_mover = mover[i - 2011][0]
    metropolitan_mover = mover[i - 2011][1]
    rural_mover = mover[i - 2011][2]

    #print(seoul_mover, metropolitan_mover, rural_mover)

    seoul_now = int((seoul_prev - seoul_mover) + seoul_mover * 0.646 + metropolitan_mover * 0.121 + rural_mover * 0.055)
    metropolitan_now = int((metropolitan_prev - metropolitan_mover) + seoul_mover * 0.246 + metropolitan_mover * 0.763 + rural_mover * 0.076)
    rural_now = int((rural_prev - rural_mover) + seoul_mover * 0.108 + metropolitan_mover * 0.116 + rural_mover * 0.869)

    print(seoul_now, metropolitan_now, rural_now)

    all_now = seoul_now + metropolitan_now + rural_now

    seoul_ratio = seoul_now / all_now
    metropolitan_ratio = metropolitan_now / all_now
    rural_ratio = rural_now / all_now

    result = f'{i}년: 서울 {seoul_ratio}, 수도권 {metropolitan_ratio},  비수도권 {rural_ratio}'
    print(result)

    seoul_prev = seoul_now
    metropolitan_prev = metropolitan_now
    rural_prev = rural_now

10108426 14899112 25726745
2011년: 서울 0.19924251220816505, 수도권 0.2936695094321132,  비수도권 0.5070879783597217
9994795 15030773 25708713
2012년: 서울 0.19700279185980776, 수도권 0.2962646302211319,  비수도권 0.5067325779190603
9888819 15161921 25683539
2013년: 서울 0.19491395551319454, 수도권 0.2988496397080956,  비수도권 0.5062364047787099
9779201 15311363 25643713
2014년: 서울 0.19275333321493868, 수도권 0.30179523401900454,  비수도권 0.5054514327660568
9655418 15454996 25623861
2015년: 서울 0.1903135109351617, 수도권 0.30462633003033945,  비수도권 0.5050601590344989
9533201 15589608 25611465
2016년: 서울 0.18790455146751484, 수도권 0.3072796114121984,  비수도권 0.5048158371202868
9428069 15717099 25589105
2017년: 서울 0.18583234650864122, 수도권 0.30979253413171015,  비수도권 0.5043751193596486
9347636 15813600 25573035
2018년: 서울 0.18424697577698515, 수도권 0.31169463339682163,  비수도권 0.5040583908261932
9281751 15906901 25545618
2019년: 서울 0.18294835029655498, 수도권 0.3135336528937935,  비수도권 0.5035179968096516
9196562 16008974 25528732
2020년: 서울 0.1812